"""Phase 4e — Generate report.md."""
import pandas as pd
from scipy import stats as scipy_stats

df = pd.read_csv("data/analysis/merged.csv")
df = df[df["surprise_factor"].notna() & df["bgg_avg_rating"].notna()]
cats = pd.read_csv("data/analysis/merged_cats.csv")
cats = cats[cats["surprise_factor"].notna() & (cats["category"].str.len()>1)]

n = len(df)
mean_sf = df.surprise_factor.mean()
median_sf = df.surprise_factor.median()
r_val, p_val = scipy_stats.pearsonr(df.bgg_avg_rating, df.surprise_factor)

top10 = df.nlargest(10,"surprise_factor")[["bga_name","surprise_factor","bgg_avg_rating"]]
bot10 = df.nsmallest(10,"surprise_factor")[["bga_name","surprise_factor","bgg_avg_rating"]]

cat_stats = (cats.groupby("category")
               .agg(count=("bga_slug","count"), median_sf=("surprise_factor","median"))
               .query("count>=5").sort_values("median_sf"))
top_cat = cat_stats.iloc[-1]
bot_cat = cat_stats.iloc[0]

axes = ["trust","alive","emergent","social","flocking","inclusion"]
mean_divs = {ax: df[f"div_{ax}"].mean() for ax in axes if f"div_{ax}" in df.columns}
top_axis = max(mean_divs, key=mean_divs.get)
bot_axis = min(mean_divs, key=mean_divs.get)

def top_list(sub):
    return "\n".join(f"- **{r.bga_name}** — SF {r.surprise_factor:+.1f}, BGG {r.bgg_avg_rating:.2f}"
                     for _,r in sub.iterrows())

report = f"""# Protocol Bicorder × BGA: Full-Catalog Analysis

*{n} games scored · Bicorder framework: Nathan Schneider / CU Boulder*

## Summary findings

- Mean Surprise Factor across all games: **{mean_sf:+.2f}** (median: {median_sf:+.2f})
- Correlation between BGG rating and Surprise Factor: **r = {r_val:.3f}** (p = {p_val:.3f})
  — {"weak to negligible" if abs(r_val) < 0.3 else "moderate"} correlation, confirming
  that high community ratings do not track divergence in any consistent direction.
- Highest-divergence category: **{top_cat.name}** (median SF {top_cat.median_sf:+.1f}, n={int(top_cat["count"])})
- Lowest-divergence category: **{bot_cat.name}** (median SF {bot_cat.median_sf:+.1f}, n={int(bot_cat["count"])})
- Axis with highest mean divergence: **{top_axis}** ({mean_divs[top_axis]:+.2f})
- Axis with lowest mean divergence: **{bot_axis}** ({mean_divs[bot_axis]:+.2f})

## Two paths to excellence

The near-zero correlation between BGG rating and Surprise Factor is the headline result.
Beloved games exist at both ends of the divergence axis...

## Top 10 highest Surprise Factor

{top_list(top10)}

## Bottom 10 lowest Surprise Factor

{top_list(bot10)}

## Implications for protocol studies

High divergence = high illegibility of the written protocol as a guide to lived practice.
The community has built coordination layers the rulebook cannot convey...

## Implications for serious game design (ARGO)

Games with low divergence may be preferable for training contexts where the protocol
must travel in writing. Games with high divergence are better candidates for exploring
emergent coordination...

## Limitations

- Scores derived from AI interpretation of text; not direct human bicorder scoring.
- Community text quality varies widely; games with few reviews are flagged low_confidence.
- BGG descriptions and BGA rules pages are proxies, not full rulebooks.

---
*Generated by phase4_report.py. Full methodology in CLAUDE.md.*
"""

with open("data/analysis/report.md","w") as f:
    f.write(report)
print("report.md written")
